version: "3.5"

services:
  api01: &api
    build:
      context: ./app
    hostname: api01
    #network_mode: host
    environment:
      - DB_HOSTNAME=db
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - API_USE_DB_FUNC=true
      - LOG_LEVEL=INFO # TODO -> Change to ERROR to test
      - PORT=8080
    ports:
      - "3001:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "220MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1